/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddScreenInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'appId' : IDL.Text,
  'screenId' : IDL.Text,
});
export const AppScreen = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const App = IDL.Record({
  'id' : IDL.Text,
  'isPublished' : IDL.Bool,
  'screens' : IDL.Vec(AppScreen),
  'owner' : IDL.Principal,
  'icon' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'screenshots' : IDL.Vec(ExternalBlob),
});
export const AddScreenshotInput = IDL.Record({
  'appId' : IDL.Text,
  'screenshot' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateAppInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const EditScreenInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'appId' : IDL.Text,
  'screenId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UploadIconInput = IDL.Record({
  'appId' : IDL.Text,
  'icon' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScreen' : IDL.Func([AddScreenInput], [App], []),
  'addScreenshot' : IDL.Func([AddScreenshotInput], [App], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApp' : IDL.Func([CreateAppInput], [App], []),
  'deleteApp' : IDL.Func([IDL.Text], [], []),
  'deleteScreen' : IDL.Func([IDL.Text, IDL.Text], [App], []),
  'editScreen' : IDL.Func([EditScreenInput], [App], []),
  'getApp' : IDL.Func([IDL.Text], [App], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'listPublishedApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'publishApp' : IDL.Func([IDL.Text], [App], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unpublishApp' : IDL.Func([IDL.Text], [App], []),
  'uploadIcon' : IDL.Func([UploadIconInput], [App], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddScreenInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'appId' : IDL.Text,
    'screenId' : IDL.Text,
  });
  const AppScreen = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const App = IDL.Record({
    'id' : IDL.Text,
    'isPublished' : IDL.Bool,
    'screens' : IDL.Vec(AppScreen),
    'owner' : IDL.Principal,
    'icon' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'screenshots' : IDL.Vec(ExternalBlob),
  });
  const AddScreenshotInput = IDL.Record({
    'appId' : IDL.Text,
    'screenshot' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateAppInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const EditScreenInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'appId' : IDL.Text,
    'screenId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UploadIconInput = IDL.Record({
    'appId' : IDL.Text,
    'icon' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScreen' : IDL.Func([AddScreenInput], [App], []),
    'addScreenshot' : IDL.Func([AddScreenshotInput], [App], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApp' : IDL.Func([CreateAppInput], [App], []),
    'deleteApp' : IDL.Func([IDL.Text], [], []),
    'deleteScreen' : IDL.Func([IDL.Text, IDL.Text], [App], []),
    'editScreen' : IDL.Func([EditScreenInput], [App], []),
    'getApp' : IDL.Func([IDL.Text], [App], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'listPublishedApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'publishApp' : IDL.Func([IDL.Text], [App], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unpublishApp' : IDL.Func([IDL.Text], [App], []),
    'uploadIcon' : IDL.Func([UploadIconInput], [App], []),
  });
};

export const init = ({ IDL }) => { return []; };