/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddScreenInput {
  'title' : string,
  'content' : string,
  'appId' : string,
  'screenId' : string,
}
export interface AddScreenshotInput {
  'appId' : string,
  'screenshot' : ExternalBlob,
}
export interface App {
  'id' : string,
  'isPublished' : boolean,
  'screens' : Array<AppScreen>,
  'icon' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
  'screenshots' : Array<ExternalBlob>,
}
export interface AppScreen {
  'id' : string,
  'title' : string,
  'content' : string,
}
export interface CreateAppInput {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface EditScreenInput {
  'title' : string,
  'content' : string,
  'appId' : string,
  'screenId' : string,
}
export type ExternalBlob = Uint8Array;
export interface UploadIconInput { 'appId' : string, 'icon' : ExternalBlob }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addScreen' : ActorMethod<[AddScreenInput], App>,
  'addScreenshot' : ActorMethod<[AddScreenshotInput], App>,
  'createApp' : ActorMethod<[CreateAppInput], App>,
  'deleteScreen' : ActorMethod<[string, string], App>,
  'editScreen' : ActorMethod<[EditScreenInput], App>,
  'getApp' : ActorMethod<[string], App>,
  'listAllApps' : ActorMethod<[], Array<App>>,
  'listPublishedApps' : ActorMethod<[], Array<App>>,
  'publishApp' : ActorMethod<[string], App>,
  'unpublishApp' : ActorMethod<[string], App>,
  'uploadIcon' : ActorMethod<[UploadIconInput], App>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];